// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// We use a plain object export for Prisma 7 compatibility 
// because the current defineConfig types in v7.8.0 are missing the directUrl property
const config = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts"
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DATABASE_URL_UNPOOLED"],
  },
};

export default config;
